GET http://localhost:8080/admin/metrics HTTP/1.1

###

GET http://localhost:8080/app/ HTTP/1.1

###

POST http://localhost:8080/api/chirps HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiNWU1Y2E1N2MtMjlhYi00YjFjLTgwMzYtNmFiNWFkMGRhOTg3IiwiZXhwIjoxNzM4MTU2Njg4LCJpYXQiOjE3MzgxNTMwODh9.A-mExUHVVtjjmOxDkkrbT3JWNe9z36T3oQnDmK5xVOE
content-type: application/json

{
    "body": "This is a kerfuffle opinion I need to share with the world",
    "user_id": "5e5ca57c-29ab-4b1c-8036-6ab5ad0da987"
}

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
    "password": "hello",
    "email": "hello@example.com"
}

###

POST http://localhost:8080/admin/reset HTTP/1.1

###

GET http://localhost:8080/api/chirps HTTP/1.1

###

GET http://localhost:8080/api/chirps/d3708544-15b0-4d95-8c5c-532861945108 HTTP/1.1

###

POST http://localhost:8080/api/login HTTP/1.1
Content-Type: application/json

{
    "password": "hello",
    "email": "hello@example.com"
}

###

POST http://localhost:8080/api/refresh HTTP/1.1
Authorization: Bearer 4b6eba683ffc33533994c9536ee21325402f484bc31a1c7f4136fecfd7bf6381
